### ISSUE TITLE
NRE on activity.WindowManager.DefaultDisplay.Rotation

### ISSUE THREAD

**Issue by O4D** [compusport/Plugin.Maui.DeviceOrientation#3]
Hello guys,

I tried 
- your Sample on my Android emulator
- your nuGet package on my own MAUI project

But I encounter an NRE.

Your sample project break on this...
![image](https://github.com/user-attachments/assets/3595f31c-02e3-4dd5-927b-2b484cb8904a)

...which seems to be the same NRE than the execution from my own app : 
![image](https://github.com/user-attachments/assets/d5260d96-dd69-4092-b912-7862e7e384a4)

Can you fix this ?

**Comment by plevie** [comment]
Is there any update on this? Went into the same situation :/

**Comment by NGumby** [comment]
Sorry about the delay, it's fixed in 1.0.2
